---
### Gradle
- name: 'verify presence of Gradle'
  stat: path={{gradle_home}}/bin/gradle
  register: gradle_installed
  when: features.gradle
  tags:
    - gradle

- name: 'install unzip'
  yum: name=unzip state=present
  when: features.gradle and ansible_os_family == 'RedHat'
  tags:
    - gradle

- name: install debian packages
  when: features.gradle and ansible_os_family == 'Debian'
  become: yes
  apt:
    name: unzip
    state: present
  tags:
    - gradle

- name: 'download Gradle'
  unarchive: copy=no src={{gradle_url}} dest=/opt validate_certs=no
  retries: 3
  when: features.gradle and not gradle_installed.stat.exists
  tags:
    - gradle

- name: 'install /etc/profile.d/gradle.sh'
  template: src=etc-profile-d-gradle-sh.j2 dest=/etc/profile.d/gradle.sh
          owner=root group=root mode=0644
  when: features.gradle
  tags:
    - gradle

- name: 'verify presence of Gradle download'
  stat: path=/tmp/{{gradle_zipfile}}
  register: gradle_download
  when: features.gradle
  tags:
    - gradle

- name: 'make sure Gradle directory is absent'
  file: dest={{gradle_home}} state=absent
  when: not features.gradle
  tags:
    - gradle

- name: 'copy simple build template'
  become: no
  template: src=build.gradle dest=~/build.gradle
  when: features.gradle
  tags:
    - gradle
    - test

- name: 'Test for presence of Gradle'
  stat: path={{gradle_home}}/bin/gradle
  when: features.gradle
  tags:
    - gradle
    - test

- name: 'set JAVA_HOME on Debian'
  become: yes
  set_fact:
    JAVA_HOME: '/usr/lib/jvm/jdk1.8.0_111'
  when: ansible_os_family == 'Debian' and features.gradle
  tags:
    - gradle
    - test

- name: 'set JAVA_HOME on RedHat'
  become: yes
  set_fact:
    JAVA_HOME: '/usr/java/jdk1.8.0_111'
  when: ansible_os_family == 'RedHat' and features.gradle
  tags:
    - gradle
    - test

- name: 'Test running Gradle'
  become: no
  environment:
    JAVA_HOME: "{{ JAVA_HOME }}"
  command: "{{gradle_home}}/bin/gradle build"
  when: features.gradle
  tags:
    - gradle
    - test

- name: 'remove Gradle test file'
  become: no
  file: dest=/home/deployer/build.gradle state=absent
  when: features.gradle
  tags:
    - gradle
    - test
